export const INTERVAL = 250;
export const IMAGE_WIDTH = 512;
export const IMAGE_QUALITY = 0.6;
export const COLUMNS = 4;
export const MAX_SCREENSHOTS = 5;
export const SILENCE_DURATION = 2500;
export const SILENT_THRESHOLD = -30;

export const TRANSPARENT_PIXEL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/wcAAwAB/2lXzAAAACV0RVh0ZGF0ZTpjcmVhdGU9MjAyMy0xMC0xOFQxNTo0MDozMCswMDowMEfahTAAAAAldEVYdGRhdGU6bW9kaWZ5PTIwMjMtMTAtMThUMTU6NDA6MzArMDA6MDBa8cKfAAAAAElFTkSuQmCC";
